INSERT INTO Band (BandName) VALUES
  ('Meatyplay'),
  ('A Dozen Times Meaty'),
  ('Bring Me the Cats'),
  ('The Poor Pixies''s Club'),
  ('Maddie Talent'),
  ('Maddie Wonder'),
  ('Poor Banana'),
  ('McBanana'),
  ('Giraffesica'),
  ('Lord of the Meaty Giraffes'),
  ('No Rest For the Pixies'),
  ('The Poor Service'),
  ('The Meaty Heroes of Brazil'),
  ('School of the A Dozen Giraffes'),
  ('The Banana Giraffes'),
  ('A Dozen Giraffes'),
  ('Wild Flying Giraffes'),
  ('The Flying Cheeks'),
  ('Banana for the Pixies'),
  ('Bananaback'),
  ('Deaf Giraffes'),
  ('Flying Dolls'),
  ('Banana, Cats and Giraffes'),
  ('The Meaty Brothers'),
  ('Meaty Banana Brigade'),
  ('Maddie and the Poor Humans'),
  ('Das Banana'),
  ('Riot of the Yellow Banana'),
  ('Maddie and the Angry Banana'),
  ('Flight of the Cats'),
  ('Au Revior Cheeks');

INSERT INTO Album (AlbumName, ReleaseDate, BandId) VALUES
  ('Like Venus on Earth', RandomDate(), RandomId()),
  ('Before Ruddy Lads', RandomDate(), RandomId()),
  ('Down With the Lads', RandomDate(), RandomId()),
  ('Ruddy, Pretty, Funny', RandomDate(), RandomId()),
  ('Gargoyle Memories', RandomDate(), RandomId()),
  ('Lads Dreams', RandomDate(), RandomId()),
  ('Mind Over Lads', RandomDate(), RandomId()),
  ('The Ruddy Side of the Torch', RandomDate(), RandomId()),
  ('Born to Chase Pigeons', RandomDate(), RandomId()),
  ('Tunnel of Lads', RandomDate(), RandomId()),
  ('Bridge Over Pretty Pigeons', RandomDate(), RandomId()),
  ('Truly, Madly, Pretty', RandomDate(), RandomId()),
  ('Mike Posner Dreams', RandomDate(), RandomId()),
  ('Torch Boogie Woogie', RandomDate(), RandomId()),
  ('Great Lads of Torch', RandomDate(), RandomId()),
  ('Torchlife', RandomDate(), RandomId()),
  ('If You''re Feeling Funny', RandomDate(), RandomId()),
  ('Ruddy Torch Etiquette', RandomDate(), RandomId()),
  ('The Torch', RandomDate(), RandomId()),
  ('Captain Gargoyle and the Lads', RandomDate(), RandomId()),
  ('Like Frabenesh on Earth', RandomDate(), RandomId()),
  ('Before Grateful Thoughts', RandomDate(), RandomId()),
  ('Down With the Thoughts', RandomDate(), RandomId()),
  ('Grateful, Snooty, Arrogant', RandomDate(), RandomId()),
  ('Zombie Memories', RandomDate(), RandomId()),
  ('Thoughts Dreams', RandomDate(), RandomId()),
  ('Mind Over Thoughts', RandomDate(), RandomId()),
  ('The Grateful Side of the Stick', RandomDate(), RandomId()),
  ('Born to Chase Cockroaches', RandomDate(), RandomId()),
  ('Tunnel of Thoughts', RandomDate(), RandomId()),
  ('Bridge Over Snooty Cockroaches', RandomDate(), RandomId()),
  ('Truly, Madly, Snooty', RandomDate(), RandomId()),
  ('Frank Sinatra Dreams', RandomDate(), RandomId()),
  ('Stick Boogie Woogie', RandomDate(), RandomId()),
  ('Great Thoughts of Stick', RandomDate(), RandomId()),
  ('Sticklife', RandomDate(), RandomId()),
  ('If You''re Feeling Arrogant', RandomDate(), RandomId()),
  ('Grateful Stick Etiquette', RandomDate(), RandomId()),
  ('The Stick', RandomDate(), RandomId()),
  ('Captain Zombie and the Thoughts', RandomDate(), RandomId()),
  ('Anonymous Saves the Day', RandomDate(), RandomId()),
  ('The Big, Blond Stick', RandomDate(), RandomId()),
  ('The Amazing Adventures of Anonymous', RandomDate(), RandomId()),
  ('King of Arrogant Thoughts', RandomDate(), RandomId()),
  ('Enemy of the Grateful Stick', RandomDate(), RandomId()),
  ('Balls to the wall', RandomDate(), RandomId()),
  ('Long story short', RandomDate(), RandomId()),
  ('Code word', RandomDate(), RandomId()),
  ('Dime in two dozen', RandomDate(), RandomId()),
  ('Crowd funding', RandomDate(), RandomId()),
  ('District zero', RandomDate(), RandomId()),
  ('Feast of nothing', RandomDate(), RandomId()),
  ('With feeling', RandomDate(), RandomId()),
  ('Class act', RandomDate(), RandomId()),
  ('No basis', RandomDate(), RandomId()),
  ('Salt and sugar', RandomDate(), RandomId()),
  ('Background check', RandomDate(), RandomId()),
  ('Kicked buckets', RandomDate(), RandomId()),
  ('Elephant in the room', RandomDate(), RandomId()),
  ('All ears', RandomDate(), RandomId()),
  ('Experience required', RandomDate(), RandomId()),
  ('Damage control', RandomDate(), RandomId()),
  ('Time flies', RandomDate(), RandomId()),
  ('Commercial brake', RandomDate(), RandomId()),
  ('No direction', RandomDate(), RandomId());


INSERT INTO Song (SongName, ReleaseDate, AlbumId) VALUES
  ('Whole Lotta Pencils', RandomDate(), RandomBandId()),
  ('Let''s Run Away to Cardiff and Swim With Pencils', RandomDate(), RandomBandId()),
  ('Straight Outta Cardiff', RandomDate(), RandomBandId()),
  ('Joystick Fields Forever', RandomDate(), RandomBandId()),
  ('Helen Eat My Crazy Pencils in Cardiff', RandomDate(), RandomBandId()),
  ('Mammas Don''t Let Your Babies Grow Up to Be Pencils', RandomDate(), RandomBandId()),
  ('Four Crazy Pencils', RandomDate(), RandomBandId()),
  ('One Angry Joystick And 200 Crazy Pencils', RandomDate(), RandomBandId()),
  ('It''s the End Of Cardiff As We Know It (And I Feel Fine)', RandomDate(), RandomBandId()),
  ('Stairway to Joystick', RandomDate(), RandomBandId()),
  ('Look Helen, this is my Joystick', RandomDate(), RandomBandId()),
  ('I plead Joystick', RandomDate(), RandomBandId()),
  ('Whole Lotta Crazy Pencils', RandomDate(), RandomBandId()),
  ('The Homecoming Queen''s Got A Joystick', RandomDate(), RandomBandId()),
  ('Somewhere Over the Joystick', RandomDate(), RandomBandId()),
  ('Like a Joystick', RandomDate(), RandomBandId()),
  ('Nice Weather For Pencils', RandomDate(), RandomBandId()),
  ('Gonna Make You Cry', RandomDate(), RandomBandId()),
  ('Joystick Deep, Pencils High', RandomDate(), RandomBandId()),
  ('My Name is Helen', RandomDate(), RandomBandId()),
  ('Can''t Take My Pencils Off You', RandomDate(), RandomBandId()),
  ('Total Eclipse of the Joystick', RandomDate(), RandomBandId()),
  ('There''s A Good Reason Pencils Are Numbered, Helen', RandomDate(), RandomBandId()),
  ('Where Have All the Pencils Gone?', RandomDate(), RandomBandId()),
  ('Don''t Eat Pencils Off The Sidewalk', RandomDate(), RandomBandId()),
  ('Joystick I Have Become', RandomDate(), RandomBandId()),
  ('Sweet Joystick O'' Mine', RandomDate(), RandomBandId()),
  ('Takin'' the Joystick Train', RandomDate(), RandomBandId()),
  ('Goody Two Pencils', RandomDate(), RandomBandId()),
  ('Cry, Cry, Cry!', RandomDate(), RandomBandId()),
  ('Great Pencils of Joystick', RandomDate(), RandomBandId()),
  ('Another Year of Pencils', RandomDate(), RandomBandId()),
  ('Livin'' on a Joystick', RandomDate(), RandomBandId()),
  ('In Joystick We Trust', RandomDate(), RandomBandId()),
  ('Bed of Pencils', RandomDate(), RandomBandId()),
  ('House of the Crazy Joystick', RandomDate(), RandomBandId()),
  ('Ghost in My Joystick', RandomDate(), RandomBandId()),
  ('Mad to Cry', RandomDate(), RandomBandId()),
  ('Cry Forever', RandomDate(), RandomBandId()),
  ('Cry - It is the Most Fun a Girl Can Have', RandomDate(), RandomBandId()),
  ('Look Helen, are you going to Cry With Me or Not?', RandomDate(), RandomBandId()),
  ('Yearning for Crazy Pencils', RandomDate(), RandomBandId()),
  ('Crazy Pencils Forever', RandomDate(), RandomBandId()),
  ('When Crazy Pencils Cry', RandomDate(), RandomBandId()),
  ('My Joystick Wants To Kill Your Mama', RandomDate(), RandomBandId()),
  ('Careful With That Joystick', RandomDate(), RandomBandId()),
  ('Pencils in My Joystick', RandomDate(), RandomBandId()),
  ('Helen Broke My Heart At Cardiff', RandomDate(), RandomBandId()),
  ('At Least Give Me My Pencils Back, You Negligent Joystick!', RandomDate(), RandomBandId()),
  ('Smells Like a Crazy Joystick', RandomDate(), RandomBandId()),
  ('You Don''t Send Me Crazy Pencils Anymore', RandomDate(), RandomBandId()),
  ('Crazy Blues', RandomDate(), RandomBandId()),
  ('Bridge Over Crazy Pencils', RandomDate(), RandomBandId()),
  ('Every Joystick You Take', RandomDate(), RandomBandId()),
  ('Welcome to Crazy Cardiff', RandomDate(), RandomBandId()),
  ('Like a Crazy Joystick', RandomDate(), RandomBandId()),
  ('Another Joystick in the Wall', RandomDate(), RandomBandId()),
  ('Joystick Autopsy', RandomDate(), RandomBandId()),
  ('You''ve Lost That Crazy Feeling', RandomDate(), RandomBandId()),
  ('Many Pieces Of Large Fuzzy Pencils Gathered Together At Cardiff And Grooving On A Joystick', RandomDate(), RandomBandId()),
  ('Rhythm of the Joystick', RandomDate(), RandomBandId()),
  ('Cry This Way', RandomDate(), RandomBandId()),
  ('Free Joystick', RandomDate(), RandomBandId()),
  ('Just Another a Crazy Joystick', RandomDate(), RandomBandId()),
  ('Hotel Cardiff', RandomDate(), RandomBandId()),
  ('The Joystick Where Your Heart Should Be', RandomDate(), RandomBandId()),
  ('Late Night Joystick', RandomDate(), RandomBandId()),
  ('Pencils Sound Better With You', RandomDate(), RandomBandId()),
  ('Cardiff on My Mind', RandomDate(), RandomBandId()),
  ('Born Crazy', RandomDate(), RandomBandId()),
  ('Good Joystick', RandomDate(), RandomBandId()),
  ('A Lot Of People Tell Me I Have A Fake Joystick', RandomDate(), RandomBandId()),
  ('Enter Helen', RandomDate(), RandomBandId()),
  ('(I Can''t Get No) Crazy Pencils', RandomDate(), RandomBandId()),
  ('Don''t Cry', RandomDate(), RandomBandId()),
  ('You''ve Lost That Crazy Joystick', RandomDate(), RandomBandId()),
  ('Hey Helen', RandomDate(), RandomBandId()),
  ('Stairway to Pencils', RandomDate(), RandomBandId()),
  ('Stand By Helen', RandomDate(), RandomBandId()),
  ('Give Me Your Pencils', RandomDate(), RandomBandId()),
  ('Stairway to Cardiff', RandomDate(), RandomBandId()),
  ('Behind Crazy Pencils', RandomDate(), RandomBandId()),
  ('Smells Like Crazy Pencils', RandomDate(), RandomBandId()),
  ('The Girl From Cardiff', RandomDate(), RandomBandId()),
  ('Great Balls of Pencils', RandomDate(), RandomBandId()),
  ('Smack My Joystick Up', RandomDate(), RandomBandId()),
  ('Baby, I Need Your Pencils', RandomDate(), RandomBandId()),
  ('We Shall Cry', RandomDate(), RandomBandId()),
  ('Here Without Helen', RandomDate(), RandomBandId()),
  ('Helen''s Waiting', RandomDate(), RandomBandId()),
  ('Stand by Your Pencils', RandomDate(), RandomBandId()),
  ('Crazy Rhapsody', RandomDate(), RandomBandId()),
  ('You Can''t Cry Through A Buffalo Herd', RandomDate(), RandomBandId()),
  ('It Hurts To Shoot Pencils From Your Joystick, But It''s Necessary', RandomDate(), RandomBandId()),
  ('Independent Joystick', RandomDate(), RandomBandId()),
  ('Crazy Joystick O'' Mine', RandomDate(), RandomBandId()),
  ('Joystick Boogie', RandomDate(), RandomBandId()),
  ('Cry? I Jolly Well Won''t Cry', RandomDate(), RandomBandId()),
  ('My Joystick Sounds Better With You', RandomDate(), RandomBandId()),
  ('Truly Madly Crazy', RandomDate(), RandomBandId()),
  ('Can''t Take My Cats Off You', RandomDate(), RandomBandId()),
  ('Let''s Run Away to Cardiff and Swim With Cats', RandomDate(), RandomBandId()),
  ('Fairy Boogie', RandomDate(), RandomBandId()),
  ('It''s the End Of Cardiff As We Know It (And I Feel Fine)', RandomDate(), RandomBandId()),
  ('Great Cats of Fairy', RandomDate(), RandomBandId()),
  ('Sleep - It is the Most Fun a Girl Can Have', RandomDate(), RandomBandId()),
  ('Give Me Your Cats', RandomDate(), RandomBandId()),
  ('Cardiff on My Mind', RandomDate(), RandomBandId()),
  ('The Girl From Cardiff', RandomDate(), RandomBandId()),
  ('Don''t Sleep', RandomDate(), RandomBandId()),
  ('You''ve Lost That Bumpy Feeling', RandomDate(), RandomBandId()),
  ('Bumpy Rhapsody', RandomDate(), RandomBandId()),
  ('Have You Met Rich?', RandomDate(), RandomBandId()),
  ('Sleep This Way', RandomDate(), RandomBandId()),
  ('Nice Weather For Cats', RandomDate(), RandomBandId()),
  ('Early Morning Fairy', RandomDate(), RandomBandId()),
  ('(I Can''t Get No) Bumpy Cats', RandomDate(), RandomBandId()),
  ('My Fairy Sounds Better With You', RandomDate(), RandomBandId()),
  ('At Least Give Me My Cats Back, You Negligent Fairy!', RandomDate(), RandomBandId()),
  ('Stairway to Fairy', RandomDate(), RandomBandId()),
  ('Cats in My Fairy', RandomDate(), RandomBandId()),
  ('Somewhere Over the Fairy', RandomDate(), RandomBandId()),
  ('Yearning for Bumpy Cats', RandomDate(), RandomBandId()),
  ('Don''t Eat Cats Off The Sidewalk', RandomDate(), RandomBandId()),
  ('Rich''s Bumpy Cats Club Band', RandomDate(), RandomBandId()),
  ('Stairway to Cats', RandomDate(), RandomBandId()),
  ('I Sleep', RandomDate(), RandomBandId()),
  ('Cardiff is Your Land', RandomDate(), RandomBandId()),
  ('Hotel Cardiff', RandomDate(), RandomBandId()),
  ('I Sleep in Your Arms', RandomDate(), RandomBandId()),
  ('Bed of Cats', RandomDate(), RandomBandId()),
  ('It Hurts To Shoot Cats From Your Fairy, But It''s Necessary', RandomDate(), RandomBandId()),
  ('Smells Like Bumpy Cats', RandomDate(), RandomBandId()),
  ('In Fairy We Trust', RandomDate(), RandomBandId()),
  ('Your Bumpy Heart', RandomDate(), RandomBandId()),
  ('Look Rich, are you going to Sleep With Me or Not?', RandomDate(), RandomBandId()),
  ('Behind Bumpy Cats', RandomDate(), RandomBandId()),
  ('Like Bumpy Cats', RandomDate(), RandomBandId()),
  ('House of the Bumpy Fairy', RandomDate(), RandomBandId()),
  ('Here Without Rich', RandomDate(), RandomBandId()),
  ('Like a Fairy', RandomDate(), RandomBandId()),
  ('Gonna Make You Sleep', RandomDate(), RandomBandId()),
  ('Baby, I Need Your Cats', RandomDate(), RandomBandId()),
  ('Just Another a Bumpy Fairy', RandomDate(), RandomBandId()),
  ('Hey Rich', RandomDate(), RandomBandId()),
  ('Great Balls of Cats', RandomDate(), RandomBandId()),
  ('Total Eclipse of the Fairy', RandomDate(), RandomBandId()),
  ('Rich Broke My Heart At Cardiff', RandomDate(), RandomBandId()),
  ('Free Fairy', RandomDate(), RandomBandId()),
  ('Whole Lotta Cats', RandomDate(), RandomBandId()),
  ('You Think I Ain''t Worth A Fairy But I Feel Like A Million Cats', RandomDate(), RandomBandId()),
  ('Look Rich, this is my Fairy', RandomDate(), RandomBandId()),
  ('Stairway to Cardiff', RandomDate(), RandomBandId()),
  ('Like a Bumpy Fairy', RandomDate(), RandomBandId()),
  ('Smells Like a Bumpy Fairy', RandomDate(), RandomBandId()),
  ('A Lot Of People Tell Me I Have A Fake Fairy', RandomDate(), RandomBandId()),
  ('Goody Two Cats', RandomDate(), RandomBandId()),
  ('There''s A Good Reason Cats Are Numbered, Rich', RandomDate(), RandomBandId()),
  ('Bridge Over Bumpy Cats', RandomDate(), RandomBandId()),
  ('They Are Night Cats! They Have Come Back From Cardiff!! Ahhhh!', RandomDate(), RandomBandId()),
  ('Every Fairy You Take', RandomDate(), RandomBandId()),
  ('Whole Lotta Bumpy Cats', RandomDate(), RandomBandId()),
  ('Cats Sound Better With You', RandomDate(), RandomBandId()),
  ('We Shall Sleep', RandomDate(), RandomBandId()),
  ('Where Have All the Cats Gone?', RandomDate(), RandomBandId()),
  ('Independent Fairy', RandomDate(), RandomBandId()),
  ('Late Night Fairy', RandomDate(), RandomBandId()),
  ('One Angry Fairy And 200 Bumpy Cats', RandomDate(), RandomBandId()),
  ('Bumpy Blues', RandomDate(), RandomBandId()),
  ('Ghost in My Fairy', RandomDate(), RandomBandId()),
  ('Rich Eat My Bumpy Cats in Cardiff', RandomDate(), RandomBandId()),
  ('Sleep, Sleep, Sleep!', RandomDate(), RandomBandId()),
  ('You Don''t Send Me Bumpy Cats Anymore', RandomDate(), RandomBandId()),
  ('Truly Madly Bumpy', RandomDate(), RandomBandId()),
  ('Bumpy Fairy O'' Mine', RandomDate(), RandomBandId()),
  ('Welcome to Bumpy Cardiff', RandomDate(), RandomBandId()),
  ('Another Fairy in the Wall', RandomDate(), RandomBandId()),
  ('The Number of your Fairy', RandomDate(), RandomBandId()),
  ('Amazing Rich', RandomDate(), RandomBandId()),
  ('Smack My Fairy Up', RandomDate(), RandomBandId()),
  ('A Song for Rich', RandomDate(), RandomBandId()),
  ('Your Cheatin'' Fairy', RandomDate(), RandomBandId()),
  ('Stand by Your Fairy', RandomDate(), RandomBandId()),
  ('Livin'' on a Fairy', RandomDate(), RandomBandId()),
  ('When Bumpy Cats Cry', RandomDate(), RandomBandId()),
  ('Fairy I Have Become', RandomDate(), RandomBandId()),
  ('Mammas Don''t Let Your Babies Grow Up to Be Cats', RandomDate(), RandomBandId()),
  ('Another Year of Cats', RandomDate(), RandomBandId()),
  ('Fairy Fields Forever', RandomDate(), RandomBandId()),
  ('Ring of Fairy', RandomDate(), RandomBandId()),
  ('Stand by Your Cats', RandomDate(), RandomBandId()),
  ('Rhythm of the Fairy', RandomDate(), RandomBandId()),
  ('Mad to Sleep', RandomDate(), RandomBandId()),
  ('Bumpy Cats Forever', RandomDate(), RandomBandId()),
  ('Takin'' the Fairy Train', RandomDate(), RandomBandId()),
  ('You Can''t Sleep Through A Buffalo Herd', RandomDate(), RandomBandId()),
  ('Sleep? I Jolly Well Won''t Sleep', RandomDate(), RandomBandId()),
  ('Rich''s Waiting', RandomDate(), RandomBandId()),
  ('The Fairy Where Your Heart Should Be', RandomDate(), RandomBandId()),
  ('Early Morning Sleep', RandomDate(), RandomBandId());
